### ISSUE TITLE
Laravel 5.7 support

### ISSUE THREAD

**Issue by GuidoHendriks** [ahuggins/open-on-make#15]
Currently the latest Laravel isn't supported. Will support be added soon?

**Comment by ahuggins** [comment]
Yeah it will be added soon. I didn't realize that 5.7 was already released.

**Comment by GuidoHendriks** [comment]
Sorry, my mistaken, it's not released yet. 🙈

But getting it ready for when it does release can't hurt. Should be there within the next 2 days.

**Comment by ahuggins** [comment]
I think this is all that needs to be done: https://github.com/ahuggins/open-on-make/releases/tag/0.0.21

If you try it and run into issues, please create a new Issue. Thanks for pointing out this change needed to happen.

**Comment by GuidoHendriks** [comment]
Should be alright, thanks! 👌🏻
