### ISSUE TITLE
5.8 Support

### ISSUE THREAD

**Issue by sunscreem** [ahuggins/open-on-make#26]
Love this package - any chance of 5.8 support being added soon?

**Comment by sunscreem** [comment]
Oops - just noticed this:

https://github.com/ahuggins/open-on-make/pull/25

**Comment by ahuggins** [comment]
Nice, hadn't seen that PR. Thanks for pointing it out. I just merged and released a new version of the package.

**Comment by sunscreem** [comment]
Awesome - composer updated and its working a treat. Nice one.
