### ISSUE TITLE
How to works with PhpStorm installed from Brew

### ISSUE THREAD

**Issue by jsilva74** [ahuggins/open-on-make#36]
Hi.

Installing PhpStorm from Brew doesn't seems to create a symlink. Is there a way to workaround this? Tried a couple of solutions what haven't worked at all.

Thanks for any help.

**Comment by ahuggins** [comment]
Did you add the environment variable for PhpStorm?

In the readme there is a section about it, you will need to add the following to your .env file:
`OPEN_ON_MAKE_EDITOR=pstorm`

**Comment by ahuggins** [comment]
and you should make sure that the `pstorm` command is available in the terminal.

Also, are you on Mac, Linux or Windows?

**Comment by jsilva74** [comment]
Thanks fro replay and sorry, I wasn't clear.

I'm on Mac and I've the environment variable in my .env. The thing is that are not pstorm or phpstorm command available (or any other equivalent) because I installed with Brew. This is what I'm trying to workaround to.

Thanks again.

**Comment by ahuggins** [comment]
Might check this out: https://www.jetbrains.com/help/phpstorm/working-with-the-ide-features-from-command-line.html#launchers-macos-linux

**Comment by jsilva74** [comment]
Thank you, that's exactly what I was looking for.
