### ISSUE TITLE
Autoload Deprecation with Composer V2

### ISSUE THREAD

**Issue by ronnorthrip** [ahuggins/open-on-make#46]
Deprecation Notice: Class OpenOnMake\OpenFile located in ./vendor/ahuggins/open-on-make/src/OpenFIle.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by ahuggins** [comment]
How did you get that error? Seems like Composer 2.0 isn't fully released yet?

**Comment by ronnorthrip** [comment]
When I composer installed the ahuggins/open-on-make. I've got composer 1.10.5.
Its probably just a deprivation warning but I thought you'd want to know.

**Comment by ahuggins** [comment]
Yeah, I just wasn't sure how to see it so that I could fix it and verify it goes away.

**Comment by ahuggins** [comment]
Fixed in 0.0.45, Thanks for pointing it out. I had the file named OpenFIle.php instead of OpenFile.php....stupid typos.
