### ISSUE TITLE
Making a test with a more complicated path doesn't open the file

### ISSUE THREAD

**Issue by ronnorthrip** [ahuggins/open-on-make#47]
Was running through a test tutorial and this failed to open the file:
php artisan make:test Http/Controllers/Auth/LoginControllerTest

This works:
php artisan make:test LoginControllerTest

And this works:
php artisan make:test Http/Controllers/Auth/LoginControllerTest.php

**Comment by ronnorthrip** [comment]
Actually this didn't work:
php artisan make:test Http/Controllers/Auth/LoginControllerTest.php

**Comment by ahuggins** [comment]
Fixed in 0.0.44
