### ISSUE TITLE
Custom make commands

### ISSUE THREAD

**Issue by eporsche** [ahuggins/open-on-make#7]
Hi,
nice extension. How should i add custom make commands to the path variable?
Currently I get sth. like this for my make:trait command - "Undefined index: trait"
Thanks

**Comment by ahuggins** [comment]
I actually have an idea about how to handle this. Let me see what I can come up with Monday or maybe Tuesday (depending on how work goes).

**Comment by ahuggins** [comment]
One thing that I see as being an issue with any customizations in a local repository...is that you have to manually maintain those in other repos. The way I envision this package is that it adds some convenience, but when it requires a lot of customization, it becomes less convenient. Ideally there would be a way to not require customizations, just for keeping this very easy to add to a project, setup the .env for the editor, and that's about it.

**Comment by eporsche** [comment]
I see your point with multiple packages coming from different repos. I am not sure how this could be handled properly. 
However it would be convenient to have the currently protected $path var in the open-on-make.php config file. That way you could easily add new paths whenever required. If a new path is required can be added in this line:
$path = base_path($this->paths[$classType] . $this->filename($event));
Instead of accessing the index of the array directly (which throws an exception if the key does not exist), it can be encapsulated with array_key_exists sending the user a warning that OpenMake will not work until a new path has been added to the config.

**Comment by andresgcarmona** [comment]
What about exporting the path variable in the config file and merge the two variables inside the handle function in the OpenOnMake listener file. Then you can easily customize/add your own paths that you have in your project.

Another way to go is using Symfony file finder to find a file inside a directory (recursive) like so:

```
$finder = new \Symfony\Component\Finder\Finder();
$finder->files()->name($filename)->in(base_path() . '/app');

foreach($finder as $file) {
   $file = $file->getRealPath();
   break;
}

if(file_exists($file)) {
	exec(
	    config('open-on-make.editor') . ' ' .
	    config('open-on-make.flags') . ' ' .
	    escapeshellcmd($file)
	);
}
```

**Comment by andresgcarmona** [comment]
I've done this (exporting the path variable in the config file) and merge the two variables inside the handle function in the OpenOnMake listener file in my fork, I'll create a PR for this.

Another way to go is using Symfony file finder to find a file inside a directory (recursive) like so:

```
$finder = new \Symfony\Component\Finder\Finder();
$finder->files()->name($filename)->in(base_path() . '/app');

foreach($finder as $file) {
   $file = $file->getRealPath();
   break;
}

if(file_exists($file)) {
	exec(
	    config('open-on-make.editor') . ' ' .
	    config('open-on-make.flags') . ' ' .
	    escapeshellcmd($file)
	);
}
```
So this way even if you don't have your paths properly configured, the listener will try to find the file inside app directory, which could be customized again in the config file too.

**Comment by ahuggins** [comment]
I think this is solved by https://github.com/ahuggins/open-on-make/pull/9/files PR, so going to close this. If this is not what you had in mind, then please let me know.
